name: Scan Images

permissions:
  actions: read
  contents: read
  security-events: write

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  scan-images:
    name: Scan ${{ matrix.image_name }} Image
    uses: Vianpyro/Template/.github/workflows/docker-image-verification.yml@main
    strategy:
      matrix:
        include:
          - image_name: devcontainer
            dockerfile_path: ./Dockerfile
            context: .devcontainer

          - image_name: production
            dockerfile_path: ./Dockerfile
            context: .
    with:
      image_name: ${{ matrix.image_name }}
      dockerfile_path: ${{ matrix.dockerfile_path }}
      context: ${{ matrix.context }}
