---
name: Enforce Correct Version Update

permissions:
  contents: read
  statuses: read

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'
      - '!**/tests/**'

jobs:
  detect:
    uses: ./.github/workflows/detect-changed-versions.yml

  check-version:
    needs: detect
    runs-on: ubuntu-latest
    if: needs.detect.outputs.versions != ''
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check __version__ changes
        run: |
          git fetch origin main
          BASE_SHA=$(git merge-base HEAD origin/main)
          for v in ${{ needs.detect.outputs.versions }}; do
            VERSION_CHANGED=$(git diff "$BASE_SHA"...HEAD -- "routes/$v/__init__.py" | grep '__version__ = ' || true)
            if [ -z "$VERSION_CHANGED" ]; then
              echo "🛑 Version $v changed, but __version__ not updated."
              exit 1
            else
              echo "✅ $v version updated."
            fi
          done
